apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-expense
spec:
  selector:
    matchLabels:
      app: api-expense
  template:
    metadata:
      labels:
        app: api-expense
    spec:
      containers:
        - name: api-expense
          image: api-expense
          imagePullPolicy: Never
          env:
            - name: PORT
              value: "8080"
          resources:
            limits:
              cpu: 500m
              memory: "512Mi"
          ports:
            - containerPort: 8080
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: api-expense
spec:
  selector:
    app: api-expense
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
